### ISSUE TITLE
Complete porting to QWebEngine

### ISSUE THREAD

**Issue by letsfindaway** [letsfindaway/OpenBoard#15]
Now as the basic porting is done and all the fundamental things are working, there is still a lot of cleanup, UI issues, unfinished features, ... In order not to fill up #14 even more, which is more discussing and describing the fundamental way of porting and the questions that arose on the way, I create this issue with a list of things to be done. Additionally I would now also like to receive bug reports from any beta testers! Feel free to create any issues here in this repository, as long as it is not merged upstream.

- [x] Reconstruct the web toolbar.<br>The web toolbar was constructed from some actions provided by the main window and additional actions and widgets (e.g. the URL entry field) added by the browser. This integration of the browser is currently broken and has to be reconstructed.
- [x] Role of the "Tools" button.<br>Reactivated to hide/show the web tools palette.
- [x] Reactivate the history functions.<br>The "Back" and "Forward" buttons had a history menu attached to them.
- [x] Use URL input field as search field, too to avoid wasting space in the toolbar.<br>If something is entered which cannot be converted to an URL, then it is considered a search term. In case the user wants to force a search, she/he can prefix the input with e.g. "?".
- [x] Configurable search engine.<br>URL with placeholder for search string.
- [x] Complete the `UBFlashTrapController`.<br>Add the features described in https://github.com/letsfindaway/OpenBoard/issues/14#issuecomment-824967278, "Proposal".
- [x] Complete porting of the widget applications.<br>Adapt them to the new asynchronous API. Moved to #20 .
- [x] Create individual widgets for oEmbed content as `UBFlashTrapController` does instead of using `AnyEmbed`.
- [x] Context menu "Open in new window" to open link in external browser. Moved to #22 .
- [x] Remove the `browser.cpp`, `browser.h` from simplewebbrowser as it is not used.
- [x] Remove unused code from `browserwindow.cpp` (setup of menu, toolbars, etc).
- [x] Remove the unused `UBStartupHintsPalette`.<br>Also remove the associated settings. Alternative is to port unused and obsolete code, which I want to avoid.
- [x] Remove the `WB` classes of the WebKit browser.
- [x] Remove any remaining references to WebKit.
