### ISSUE TITLE
[Feature Request] Snap to grid

### ISSUE THREAD

**Issue by letsfindaway** [letsfindaway/OpenBoard#170]
**Is your feature request related to a problem? Please describe.**

When using a background grid it is often desirable to have items aligned to the grid: lines, the center and tip of the compass, axes, text etc. OTOH people also want those things without alignment, see e.g. #145.

**Describe the solution you'd like**

Users should be able to choose between aligned and unaligned positioning. I propose using a modifier key (preferred: Shift) to switch between aligned and unaligned positioning: Without the key, the items are not aligned. When this key is pressed while releasing the mouse button, alignment is enforced.

Snapping should be "live" while moving the mouse, so that the user sees the effect while positioning, just as it is for the "angle grip" function when drawing a line. It should not be as in the current Axes tool, where the effect is only visible after releasing the mouse.

**Describe alternatives you've considered**

There could be a dedicated button at the delegate for specific tools which switches between "magnetic" and normal mode.

**Additional context**

The solution should also work with the new configurable background grid #151. This means that the magnetic points have to be computed by the grid. I propose that each line of the grid has some magnetism. At a crossing, it doubles. This allows even an isometric grid to be magnetic in the way the user expects. There should be a configuration variable for the magnetic force.

The force should be a function of distance (in view coordinates) and vanish at some threshold distance. This would even allow a natural behavior at the millimeter grid. Taking this as an example we could even try to make the force depending on the width and alpha color value of the line.

As the proposed implementation depends on the configurable background it has to be implemented after or together with this feature. The `UBBackgroundManager` would get a new function

```c++
QPointF snap(const QPointF& point, double* force = nullptr) const;
```

computing the snap position and optionally returning the snap force. Argument and return value are in scene coordinates. Each object has to decide how to use this function. So snapping an image (all four corners?) could behave differently from snapping a line (line end points).

**Comment by letsfindaway** [comment]
**Additional idea**

This could even enhance the "grip" function from `UBGraphicsScene`, which helps aligning a line with angles of 0°, 45°, 90° etc. My proposal would be to extend the background grid specification by a set of snapping angles. Isometric grid could e.g. choose 30° and 60° and omit 45°.

**Comment by letsfindaway** [comment]
The `UBBackgroundManager::snap()` function mentioned above for the flexible background could also be implemented in the `UBGraphicsScene`, which delegates it further to the `UBBackgroundManager`. This would allow to adapt all tools already before the flexible background is merged. The scene has all information necessary to perform this function and is easily accessible from each tool.

**Comment by letsfindaway** [comment]
Now back from implementation to the user perspective.

## Snapping behavior

| Tool | Draw | Move | Resize | Rotate |
| --- | --- | --- | --- | --- |
| Pen | - | - | - | - |
| Line | Start/end at grid | = | = | N/A |
| Ruler | Top 0 at grid | = | - | see below |
| Protractor | 0 at grid | = | - | - |
| Triangle | 0 at grid | = | - | - |
| Compass | center at grid | = | pen at grid | - |
| Axes | 0/0 at grid | = | - | N/A |
| Objects | top/left at grid | Each corner at grid | Resized side at grid | Snap to angle (15° steps) |

- \- means no snap
- = means same as while drawing
- N/A means not supported for that tool

### Line tool

For the line tool, we have some more special effects:

- The snap to angle is no longer necessary as it is automatically achieved by snap to grid.
- A Move or a Resize snaps either the starting point or the end point depending on where the line is fetched.
- Resize no longer affects thickness of line.
- There is no rotate any longer. Instead the end points of the line can be dragged individually using some drag indicators on the delegate at the end points of the line.
- When using the finger, the line can be fetched at the end points (to move them individually) or in the middle (to move the line). 

### Ruler

For the ruler we introduce a special behavior for rotate. It snaps the top line of the ruler to the grid point closest to the current mouse position.

### Objects

As soon as an object is in a rotated state, it no longer snaps on resizes.

**Comment by letsfindaway** [comment]
# TODOs

- [ ] Apply margin corrections before transforming to scene coordinates.
- [ ] Apply margin corrections also in `UBDelegateFrame`.
- [ ] Implement snapping on move in `UBDelegateFrame`.

**Comment by letsfindaway** [comment]
# Questions

- [ ] How shall the current 45°/90° snap be integrated? It is still useful, at least on a blank background but probably in other situations, too. Note that there is one big difference to the snap-to-grid: it snaps the angle only, no matter where the starting point is related to the grid. We need to find a solution with the least surprise.
  - We could make the behavior depending on whether the starting point was snapped. If we already pressed shift when starting the line, then we also snap the end point to the grid, if Shift is still pressed. If the starting point was at an arbitrary position and we press Shift later, then we use the 45°/90° snap.
  - We could only use the 45°/90° snap for a blank background, where snap-to-grid is a no-op.
  - We could use another modifier, e.g. Alt, for the 45°/90° snap.
  - We could add a directional snap additionally to the snap-to-grid function. This would mean that also for a grid or line background we could draw horizontal lines which are not aligned to the grid. This is only effective for drawing lines.

  The last option sounds like an interesting approach!

**Comment by letsfindaway** [comment]
Discussion moved to PR, closing this one here.
