### ISSUE TITLE
Deployment checklist

### ISSUE THREAD

**Issue by letsfindaway** [letsfindaway/OpenBoard#92]
List of branches and branch status, planning for openSUSE builds.

**Comment by letsfindaway** [comment]
## Branch prioritization

- [ ] [add-cmake-build-system](https://github.com/letsfindaway/OpenBoard/tree/add-cmake-build-system/)
- [ ] [refactor-qt6](https://github.com/letsfindaway/OpenBoard/tree/refactor-qt6)
- [ ] [check-widget-compatibility](https://github.com/letsfindaway/OpenBoard/tree/check-widget-compatibility)
- [ ] [improve-pdf-export-scaling](https://github.com/letsfindaway/OpenBoard/tree/improve-pdf-export-scaling)
- [ ] [fix-675-widget-freeze](https://github.com/letsfindaway/OpenBoard/tree/fix-675-widget-freeze)
- [ ] [chore-rework-linux-build](https://github.com/letsfindaway/OpenBoard/tree/chore-rework-linux-build)
- [ ] [improve-displaymanager](https://github.com/letsfindaway/OpenBoard/tree/improve-displaymanager)
- [ ] [ffmpeg-new-api](https://github.com/letsfindaway/OpenBoard/tree/ffmpeg-new-api)
- [ ] [maintain-compatibility-with-qt5-12](https://github.com/letsfindaway/OpenBoard/tree/maintain-compatibility-with-qt5-12)
- [ ] [scale-mirror-pixmap](https://github.com/letsfindaway/OpenBoard/tree/scale-mirror-pixmap)
- [ ] [common-background-drawing](https://github.com/letsfindaway/OpenBoard/tree/common-background-drawing)
- [ ] [fix-memory-leak-UBSvgSubsetAdaptor](https://github.com/letsfindaway/OpenBoard/tree/fix-memory-leak-UBSvgSubsetAdaptor)
- [ ] [cleanup-unused-files](https://github.com/letsfindaway/OpenBoard/tree/cleanup-unused-files)
- [ ] [shortcut-configuration](https://github.com/letsfindaway/OpenBoard/tree/shortcut-configuration)
- [ ] [chore-add-issue-templates](https://github.com/letsfindaway/OpenBoard/tree/chore-add-issue-templates)
- [ ] [webpage-lifecycle](https://github.com/letsfindaway/OpenBoard/tree/webpage-lifecycle)

**Comment by letsfindaway** [comment]
## Release planning for "Experimental"

The next "experimental" release on openSUSE shall include the following patches:

- Based on current `dev`. This means that all patches have to be updated, as they have been rebased.
- 460 Shortcut configuration
- 551 refactor: drawBackground mostly in scene
- 569 fix: scaling of mirror pixmap
- 633 Improve displaymanager

### Updated patches

- 651 chore: reorganize linux build (shall be updated to correctly handle `/etc`)

### New patches

- 677 fix: size of exported PDF page
- 680 Webpage lifecycle
- 681 feat: open ubz file in running instance
- 683 Improve on-screen keyboard handling (carved out from 651)

the following PRs have been merged to `dev` and will no longer be included as patches:

- 628 Problem after removing the ruler from the board
- 637 fix: restore PDF background export
- 641 Fix font handling
- 649 fix: scaling of background PDF during export

**Comment by letsfindaway** [comment]
This issue is no longer appropriate for the future development.
